/** Every PostHog event name the desktop client may send. `trackEvent` takes
 * this union instead of `string` so a typo fails `tsc` rather than shipping
 * a silently unmatched event. The same names live in the cross-repo contract
 * (`juno-backend` funnel_events.py and the Flutter funnel_events.dart); add
 * a name there in the same change that adds it here. */
export type AnalyticsEvent =
  // Lifecycle and onboarding
  | "desktop_app_launched"
  | "desktop_install_observed"
  | "desktop_onboarding_step_completed"
  | "desktop_onboarding_completed"
  | "desktop_telemetry_consent_accepted"
  | "desktop_onboarding_auth_path_selected"
  | "desktop_privacy_setup_saved"
  | "desktop_hotkey_test_passed"
  | "desktop_hotkey_test_skipped"
  | "desktop_hotkey_tour_completed"
  | "desktop_agent_demo_started"
  | "desktop_agent_demo_finished"
  | "desktop_agent_demo_timed_out"
  // Auth
  | "desktop_sign_in_started"
  | "desktop_sign_in_completed"
  | "desktop_sign_in_failed"
  | "desktop_signed_out"
  | "web_auth_started"
  | "web_auth_completed"
  | "web_auth_failed"
  | "web_auth_expired"
  | "web_auth_cancelled"
  // Billing
  | "desktop_checkout_started"
  | "desktop_checkout_upgraded"
  | "desktop_checkout_deadline"
  // Notifications
  | "desktop_notification_fetched"
  | "desktop_notification_queued"
  | "desktop_notification_toast_shown"
  | "desktop_notification_toast_denied"
  | "desktop_notification_backlog_summary_toast_shown"
  | "desktop_notification_dismissed"
  | "desktop_notification_page_dropped"
  // Voice
  | "voice_session_started"
  | "voice_session_ended"
  | "voice_first_response"
  | "voice_error"
  | "voice_retry_attempt"
  | "voice_retry_exhausted"
  | "voice_start_failed"
  // Chat, draft, callback, capture
  | "chat_session_started"
  | "chat_message_sent"
  | "chat_e2e_latency"
  | "chat_turn_failed"
  | "draft_card_copied"
  | "draft_card_dismissed"
  | "callback_card_shown"
  | "callback_card_engaged_10s"
  | "callback_card_dismissed"
  | "callback_card_toggle_off"
  | "callback_chip_deleted"
  | "turn_context_upload"
  | "screen_sight_toggled"
  // Meetings
  | "meeting_auto_summon"
  | "meeting_ticker_dismissed"
  | "meeting_alerts_toggle_off"
  | "meeting_notes_arm_toggled"
  | "meeting_notes_auto_toggled"
  | "meeting_capture_started"
  | "meeting_capture_manual"
  | "meeting_capture_completed"
  | "meeting_capture_failed"
  | "meeting_cap_blocked"
  | "meeting_upload_attempt"
  | "meeting_note_card_shown"
  | "meeting_note_card_dismissed"
  | "meeting_note_card_toggle_off"
  // Guide Mode
  | "guide_session"
  | "guide_completed"
  | "guide_abandoned"
  | "guide_steps_received"
  | "guide_auto_frames_sent"
  | "guide_agent_timeouts"
  // Interview Companion
  | "interview_companion_session_started"
  | "interview_companion_session_ended"
  | "interview_companion_turn_latency"
  | "interview_companion_first_answer_text"
  | "interview_companion_answer_completed"
  | "interview_companion_question_decision"
  | "interview_companion_resume_attached"
  | "interview_companion_credential_rotation"
  | "interview_companion_screen_sight"
  | "interview_companion_reflection"
  | "interview_companion_recovery"
  | "interview_companion_error"
  // Dictation
  | "desktop_dictation_share_drain"
  | "dictation_hold_completed"
  // Updater
  | "desktop_update_available"
  | "desktop_update_check_failed"
  | "desktop_update_install_started"
  | "desktop_update_install_result"
  // Permissions, feedback, health
  | "desktop_permission_result"
  | "feedback_submitted"
  | "desktop_heartbeat"
  | "desktop_startup_diagnostics_sent"
  | "client_log";
