name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci

      - run: npx tsc --noEmit

      - run: npx audit-ci --config ./audit-ci.jsonc

  rust:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo check
        working-directory: src-tauri

      - run: cargo install cargo-audit --locked

      - run: cargo audit
        working-directory: src-tauri
